from __future__ import annotations

from typing import Any


TOOL_PRESET_DEFAULTS: dict[str, dict[str, Any]] = {
	"websearch": {
		"label": "Web Search (DuckDuckGo)",
		"third_party": "Web",
		"config_fields": [
			{
				"key": "provider",
				"label": "Provider",
				"input": "text",
				"required": True,
				"default": "duckduckgo",
			},
			{
				"key": "region",
				"label": "Region",
				"input": "text",
				"required": True,
				"default": "wt-wt",
				"placeholder": "wt-wt, us-en, vn-vi",
			},
			{
				"key": "safesearch",
				"label": "Safe Search",
				"input": "select",
				"required": True,
				"default": "moderate",
				"options": ["off", "moderate", "strict"],
			},
		],
	},
	"parallel_search": {
		"label": "Web Search (Parallel AI)",
		"third_party": "Web",
		"config_fields": [
			{
				"key": "api_key",
				"label": "Parallel API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to PARALLEL_API_KEY",
			},
			{
				"key": "beta_header",
				"label": "Beta Header",
				"input": "text",
				"required": False,
				"default": "search-extract-2025-10-10",
			},
		],
	},
	"brave_search": {
		"label": "Web Search (Brave Search)",
		"third_party": "Web",
		"config_fields": [
			{
				"key": "api_key",
				"label": "Brave Search API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to BRAVE_SEARCH_API_KEY",
			},
			{
				"key": "use_llm_context",
				"label": "Use LLM Context",
				"input": "boolean",
				"required": False,
				"default": False,
			},
		],
	},
	"openrouter_search": {
		"label": "Web Search (OpenRouter Sonar)",
		"third_party": "Web",
		"config_fields": [
			{
				"key": "api_key",
				"label": "OpenRouter API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to OPENROUTER_API_KEY",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "perplexity/sonar-pro",
			},
		],
	},
	"http": {
		"label": "HTTP Client",
		"third_party": "Network",
		"config_fields": [
			{
				"key": "timeout",
				"label": "Timeout (seconds)",
				"input": "text",
				"required": False,
				"default": "30",
				"placeholder": "30",
			},
			{
				"key": "retries",
				"label": "Retries",
				"input": "text",
				"required": False,
				"default": "5",
				"placeholder": "5",
			},
			{
				"key": "user_agent",
				"label": "User Staff",
				"input": "text",
				"required": False,
				"default": "ai-collective/http-tool",
			},
		],
	},
	"mcp": {
		"label": "MCP Server (Model Context Protocol)",
		"third_party": "MCP",
		"config_fields": [
			{
				"key": "transport",
				"label": "Transport",
				"input": "select",
				"required": True,
				"default": "stdio",
				"options": ["stdio", "streamable_http", "sse"],
			},
			{
				"key": "command",
				"label": "Command (stdio)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "npx | uvx | python — required for stdio transport",
			},
			{
				"key": "args",
				"label": "Arguments (stdio)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": '-y @modelcontextprotocol/server-filesystem /tmp  (space-separated or JSON array)',
			},
			{
				"key": "env",
				"label": "Environment Variables (stdio)",
				"input": "textarea",
				"required": False,
				"default": "",
				"rows": 3,
				"placeholder": 'KEY=VALUE per line, or JSON object {"KEY": "VALUE"}',
			},
			{
				"key": "url",
				"label": "Server URL (streamable_http / sse)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "http://localhost:8000/mcp — required for HTTP transports",
			},
			{
				"key": "headers",
				"label": "HTTP Headers (streamable_http / sse)",
				"input": "textarea",
				"required": False,
				"default": "",
				"rows": 3,
				"placeholder": 'Authorization=Bearer xxx per line, or JSON object',
			},
			{
				"key": "allowed_tools",
				"label": "Allowed Tools (whitelist)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional comma-separated tool names; empty = expose all",
			},
			{
				"key": "timeout_seconds",
				"label": "Tool Call Timeout (seconds)",
				"input": "text",
				"required": False,
				"default": "60",
				"placeholder": "60",
			},
		],
	},
	"a2a": {
		"label": "A2A Staff (Agent2Agent)",
		"third_party": "A2A",
		"config_fields": [
			{
				"key": "url",
				"label": "Staff URL",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "https://other-staff.example.com  (base URL or staff-card .json)",
			},
			{
				"key": "headers",
				"label": "HTTP Headers (auth)",
				"input": "textarea",
				"required": False,
				"default": "",
				"rows": 3,
				"placeholder": 'Authorization=Bearer xxx per line, or JSON object',
			},
			{
				"key": "timeout_seconds",
				"label": "Call Timeout (seconds)",
				"input": "text",
				"required": False,
				"default": "60",
				"placeholder": "60",
			},
			{
				"key": "poll_interval_seconds",
				"label": "Task Poll Interval (seconds)",
				"input": "text",
				"required": False,
				"default": "1.5",
				"placeholder": "1.5",
			},
		],
	},
	"browser": {
		"label": "Browser Automation",
		"third_party": "Browser",
		"config_fields": [
			{
				"key": "driver",
				"label": "Driver",
				"input": "text",
				"required": True,
				"default": "browser_use",
			},
			{
				"key": "cdp_url",
				"label": "CDP URL",
				"input": "text",
				"required": True,
				"default": "http://localhost:9222",
			},
			{
				"key": "requires_runtime",
				"label": "Requires Runtime",
				"input": "boolean",
				"required": False,
				"default": True,
			},
		],
	},
	"bash": {
		"label": "Shell Automation",
		"third_party": "Shell",
		"config_fields": [
			{
				"key": "sandbox",
				"label": "Sandbox",
				"input": "text",
				"required": True,
				"default": "default",
			},
			{
				"key": "requires_runtime",
				"label": "Requires Runtime",
				"input": "boolean",
				"required": False,
				"default": True,
			},
		],
	},
	"youtube": {
		"label": "YouTube Search (yt-dlp)",
		"third_party": "YouTube",
		"config_fields": [
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"xai": {
		"label": "xAI X Search",
		"third_party": "X (xAI)",
		"config_fields": [
			{
				"key": "api_key",
				"label": "xAI API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to XAI_API_KEY",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "grok-4-fast",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"xiaohongshu": {
		"label": "Xiaohongshu Search",
		"third_party": "Xiaohongshu",
		"config_fields": [
			{
				"key": "base_url",
				"label": "API Base URL",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to XIAOHONGSHU_API_BASE_URL",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"truthsocial": {
		"label": "Truth Social Search",
		"third_party": "Truth Social",
		"config_fields": [
			{
				"key": "token",
				"label": "Truth Social Token",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to TRUTHSOCIAL_TOKEN",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"bluesky": {
		"label": "Bluesky Search",
		"third_party": "Bluesky",
		"config_fields": [
			{
				"key": "handle",
				"label": "Bluesky Handle",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to BSKY_HANDLE",
			},
			{
				"key": "app_password",
				"label": "Bluesky App Password",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to BSKY_APP_PASSWORD",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"bird_x": {
		"label": "X Search (Bird GraphQL)",
		"third_party": "X (Bird)",
		"config_fields": [
			{
				"key": "auth_token",
				"label": "X AUTH_TOKEN",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to AUTH_TOKEN",
			},
			{
				"key": "ct0",
				"label": "X CT0",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to CT0",
			},
			{
				"key": "bird_search_mjs",
				"label": "bird-search.mjs Path",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to BIRD_SEARCH_MJS or project default",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"tiktok": {
		"label": "TikTok Search (ScrapeCreators)",
		"third_party": "TikTok",
		"config_fields": [
			{
				"key": "token",
				"label": "ScrapeCreators API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SCRAPECREATORS_API_KEY",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"scrapecreators_x": {
		"label": "X Search (ScrapeCreators)",
		"third_party": "X (ScrapeCreators)",
		"config_fields": [
			{
				"key": "token",
				"label": "ScrapeCreators API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SCRAPECREATORS_API_KEY",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"instagram": {
		"label": "Instagram Reels Search (ScrapeCreators)",
		"third_party": "Instagram",
		"config_fields": [
			{
				"key": "token",
				"label": "ScrapeCreators API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SCRAPECREATORS_API_KEY",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"reddit": {
		"label": "Reddit Search (ScrapeCreators)",
		"third_party": "Reddit",
		"config_fields": [
			{
				"key": "token",
				"label": "ScrapeCreators API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SCRAPECREATORS_API_KEY",
			},
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"reddit_enrich": {
		"label": "Reddit Enrich (Thread Metrics)",
		"third_party": "Reddit",
		"config_fields": [
			{
				"key": "token",
				"label": "ScrapeCreators API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SCRAPECREATORS_API_KEY",
			},
			{
				"key": "backend",
				"label": "Backend",
				"input": "select",
				"required": True,
				"default": "auto",
				"options": ["auto", "scrapecreators", "reddit_json"],
			},
		],
	},
	"hackernews": {
		"label": "Hacker News Search (Algolia)",
		"third_party": "Hacker News",
		"config_fields": [
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"polymarket": {
		"label": "Polymarket Search (Gamma API)",
		"third_party": "Polymarket",
		"config_fields": [
			{
				"key": "depth",
				"label": "Search Depth",
				"input": "select",
				"required": True,
				"default": "default",
				"options": ["quick", "default", "deep"],
			},
		],
	},
	"promt_tool": {
		"label": "Prompt Tool",
		"third_party": "Prompt",
		"config_fields": [
			{
				"key": "system_prompt",
				"label": "System Prompt",
				"input": "textarea",
				"required": True,
				"default": "",
				"rows": 6,
			},
		],
	},
	"sheet": {
		"label": "Google Sheets",
		"third_party": "Google",
		"config_fields": [],
	},
	"drive": {
		"label": "Google Drive",
		"third_party": "Google",
		"config_fields": [],
	},
	"docs": {
		"label": "Google Docs",
		"third_party": "Google",
		"config_fields": [],
	},
	"slides": {
		"label": "Google Slides",
		"third_party": "Google",
		"config_fields": [],
	},
	"calendar": {
		"label": "Google Calendar",
		"third_party": "Google",
		"config_fields": [],
	},
	"telegram_messaging": {
		"label": "Telegram Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "bot_token",
				"label": "Bot Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to TELEGRAM_BOT_TOKEN",
			},
			{
				"key": "default_chat_id",
				"label": "Default Chat ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to TELEGRAM_CHAT_ID",
			},
		],
	},
	"discord_messaging": {
		"label": "Discord Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "bot_token",
				"label": "Bot Token",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to DISCORD_BOT_TOKEN",
			},
			{
				"key": "webhook_url",
				"label": "Webhook URL",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to DISCORD_WEBHOOK_URL",
			},
			{
				"key": "default_channel_id",
				"label": "Default Channel ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to DISCORD_CHANNEL_ID",
			},
		],
	},
	"slack_messaging": {
		"label": "Slack Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "bot_token",
				"label": "Bot Token (xoxb-...)",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to SLACK_BOT_TOKEN",
			},
			{
				"key": "default_channel",
				"label": "Default Channel",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "#general or channel ID, fallback to SLACK_DEFAULT_CHANNEL",
			},
		],
	},
	"teams_messaging": {
		"label": "Microsoft Teams",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "webhook_url",
				"label": "Incoming Webhook URL",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to TEAMS_WEBHOOK_URL",
			},
		],
	},
	"whatsapp_business": {
		"label": "WhatsApp Business",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "access_token",
				"label": "Meta Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to WHATSAPP_ACCESS_TOKEN",
			},
			{
				"key": "phone_number_id",
				"label": "Phone Number ID",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to WHATSAPP_PHONE_NUMBER_ID",
			},
		],
	},
	"facebook_messenger": {
		"label": "Facebook Messenger",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "page_access_token",
				"label": "Page Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to MESSENGER_PAGE_ACCESS_TOKEN",
			},
		],
	},
	"instagram_messaging": {
		"label": "Instagram Messaging",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "page_access_token",
				"label": "Page Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to INSTAGRAM_PAGE_ACCESS_TOKEN",
			},
			{
				"key": "ig_user_id",
				"label": "Instagram User ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to INSTAGRAM_USER_ID",
			},
		],
	},
	"line_messaging": {
		"label": "LINE Official Account",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "channel_access_token",
				"label": "Channel Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to LINE_CHANNEL_ACCESS_TOKEN",
			},
		],
	},
	"viber_messaging": {
		"label": "Viber Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "auth_token",
				"label": "Auth Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to VIBER_AUTH_TOKEN",
			},
			{
				"key": "sender_name",
				"label": "Sender Display Name",
				"input": "text",
				"required": False,
				"default": "AI Assistant",
				"placeholder": "Optional, fallback to VIBER_SENDER_NAME",
			},
		],
	},
	"zalo_messaging": {
		"label": "Zalo Official Account",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "access_token",
				"label": "OA Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to ZALO_OA_ACCESS_TOKEN",
			},
		],
	},
	"signal_messaging": {
		"label": "Signal (CallMeBot)",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "phone_number",
				"label": "Phone Number",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "+84901234567, fallback to SIGNAL_PHONE_NUMBER",
			},
			{
				"key": "api_key",
				"label": "CallMeBot API Key",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Register at signal.callmebot.com, fallback to SIGNAL_CALLMEBOT_API_KEY",
			},
		],
	},
	"skype_messaging": {
		"label": "Skype Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "app_id",
				"label": "Bot App ID",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to SKYPE_BOT_APP_ID",
			},
			{
				"key": "app_password",
				"label": "Bot App Password",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to SKYPE_BOT_APP_PASSWORD",
			},
			{
				"key": "conversation_id",
				"label": "Conversation ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SKYPE_CONVERSATION_ID",
			},
		],
	},
	"wire_messaging": {
		"label": "Wire Bot",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "bearer_token",
				"label": "Bearer Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to WIRE_BEARER_TOKEN",
			},
			{
				"key": "bot_conversation_id",
				"label": "Default Conversation ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to WIRE_CONVERSATION_ID",
			},
		],
	},
	"wechat_messaging": {
		"label": "WeChat Official Account",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "app_id",
				"label": "App ID",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to WECHAT_APP_ID",
			},
			{
				"key": "app_secret",
				"label": "App Secret",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to WECHAT_APP_SECRET",
			},
		],
	},
	"snapchat_messaging": {
		"label": "Snapchat Ads",
		"third_party": "Messaging",
		"config_fields": [
			{
				"key": "access_token",
				"label": "Access Token",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Optional, fallback to SNAPCHAT_ACCESS_TOKEN",
			},
			{
				"key": "ad_account_id",
				"label": "Ad Account ID",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to SNAPCHAT_AD_ACCOUNT_ID",
			},
		],
	},
	"image_generation": {
		"label": "Image Generation (OpenAI-compatible)",
		"third_party": "AI Media",
		"config_fields": [
			{
				"key": "api_key",
				"label": "API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to IMAGE_GEN_API_KEY / OPENAI_API_KEY",
			},
			{
				"key": "endpoint",
				"label": "Endpoint",
				"input": "text",
				"required": False,
				"default": "https://api.openai.com/v1/images/generations",
				"placeholder": "Any OpenAI-compatible image generations URL",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "gpt-image-1",
				"placeholder": "gpt-image-1, dall-e-3, ...",
			},
			{
				"key": "size",
				"label": "Default Size",
				"input": "text",
				"required": False,
				"default": "1024x1024",
				"placeholder": "1024x1024, 1024x1536, 1536x1024",
			},
		],
	},
	"text_to_speech": {
		"label": "Text-to-Speech / Voiceover (OpenAI-compatible)",
		"third_party": "AI Media",
		"config_fields": [
			{
				"key": "api_key",
				"label": "API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to TTS_API_KEY / OPENAI_API_KEY",
			},
			{
				"key": "endpoint",
				"label": "Endpoint",
				"input": "text",
				"required": False,
				"default": "https://api.openai.com/v1/audio/speech",
				"placeholder": "Any OpenAI-compatible audio speech URL",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "gpt-4o-mini-tts",
				"placeholder": "gpt-4o-mini-tts, tts-1, ...",
			},
			{
				"key": "voice",
				"label": "Voice",
				"input": "text",
				"required": False,
				"default": "alloy",
				"placeholder": "alloy, verse, coral, ...",
			},
			{
				"key": "audio_format",
				"label": "Audio Format",
				"input": "select",
				"required": False,
				"default": "mp3",
				"options": ["mp3", "wav", "opus", "aac", "flac"],
			},
			{
				"key": "output_dir",
				"label": "Output Directory (optional)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "If set, saves audio files here and returns the path",
			},
		],
	},
	"video_generation": {
		"label": "Video Generation (async create + poll)",
		"third_party": "AI Media",
		"config_fields": [
			{
				"key": "api_key",
				"label": "API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to VIDEO_GEN_API_KEY",
			},
			{
				"key": "create_endpoint",
				"label": "Create Endpoint",
				"input": "text",
				"required": True,
				"default": "",
				"placeholder": "Your provider's job-creation URL (POST)",
			},
			{
				"key": "status_endpoint",
				"label": "Status Endpoint",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Poll URL with {id} placeholder, e.g. https://api/x/jobs/{id}",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "video-gen-1",
				"placeholder": "Provider model name",
			},
			{
				"key": "poll_interval_seconds",
				"label": "Poll Interval (seconds)",
				"input": "text",
				"required": False,
				"default": "5",
			},
			{
				"key": "max_wait_seconds",
				"label": "Max Wait (seconds)",
				"input": "text",
				"required": False,
				"default": "300",
			},
		],
	},
	"gemini_image": {
		"label": "Gemini Image (Imagen)",
		"third_party": "Google Gemini",
		"config_fields": [
			{
				"key": "api_key",
				"label": "Gemini API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to GEMINI_API_KEY / GOOGLE_API_KEY",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "imagen-3.0-generate-002",
				"placeholder": "imagen-3.0-generate-002, imagen-4.0-generate-001, ...",
			},
			{
				"key": "aspect_ratio",
				"label": "Default Aspect Ratio",
				"input": "select",
				"required": False,
				"default": "1:1",
				"options": ["1:1", "9:16", "16:9", "3:4", "4:3"],
			},
			{
				"key": "base_url",
				"label": "API Base URL",
				"input": "text",
				"required": False,
				"default": "https://generativelanguage.googleapis.com/v1beta",
			},
		],
	},
	"gemini_tts": {
		"label": "Gemini Text-to-Speech",
		"third_party": "Google Gemini",
		"config_fields": [
			{
				"key": "api_key",
				"label": "Gemini API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to GEMINI_API_KEY / GOOGLE_API_KEY",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "gemini-2.5-flash-preview-tts",
				"placeholder": "gemini-2.5-flash-preview-tts, gemini-2.5-pro-preview-tts",
			},
			{
				"key": "voice",
				"label": "Voice",
				"input": "text",
				"required": False,
				"default": "Kore",
				"placeholder": "Kore, Puck, Charon, Aoede, ...",
			},
			{
				"key": "output_dir",
				"label": "Output Directory (optional)",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "If set, saves WAV files here and returns the path",
			},
			{
				"key": "base_url",
				"label": "API Base URL",
				"input": "text",
				"required": False,
				"default": "https://generativelanguage.googleapis.com/v1beta",
			},
		],
	},
	"gemini_video": {
		"label": "Gemini Video (Veo)",
		"third_party": "Google Gemini",
		"config_fields": [
			{
				"key": "api_key",
				"label": "Gemini API Key",
				"input": "text",
				"required": False,
				"default": "",
				"placeholder": "Optional, fallback to GEMINI_API_KEY / GOOGLE_API_KEY",
			},
			{
				"key": "model",
				"label": "Model",
				"input": "text",
				"required": False,
				"default": "veo-3.0-generate-preview",
				"placeholder": "veo-3.0-generate-preview, veo-2.0-generate-001, ...",
			},
			{
				"key": "poll_interval_seconds",
				"label": "Poll Interval (seconds)",
				"input": "text",
				"required": False,
				"default": "10",
			},
			{
				"key": "max_wait_seconds",
				"label": "Max Wait (seconds)",
				"input": "text",
				"required": False,
				"default": "300",
			},
			{
				"key": "base_url",
				"label": "API Base URL",
				"input": "text",
				"required": False,
				"default": "https://generativelanguage.googleapis.com/v1beta",
			},
		],
	},
}


def build_tool_presets(tool_names: list[str]) -> list[dict[str, Any]]:
	presets: list[dict[str, Any]] = []
	for tool_name in tool_names:
		preset = TOOL_PRESET_DEFAULTS.get(tool_name, {})
		title = tool_name.replace("_", " ").replace("-", " ").strip().title()
		presets.append(
			{
				"tool_name": tool_name,
				"label": preset.get("label") or title,
				"third_party": preset.get("third_party") or title,
				"config_fields": list(preset.get("config_fields") or []),
			}
		)
	return presets
