#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
err()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: k3s sandbox image survives reboot
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

IMAGE="enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:latest"
CACHE_DIR="$HOME/.k3s-image-cache"
TAR_PATH="$CACHE_DIR/sandbox-all-in-one.tar"
UNIT_PATH="/etc/systemd/system/k3s-sandbox-image-warmup.service"

banner "k3s sandbox image — survive reboot"
say "Máy này reboot rất thường xuyên, và mỗi lần k3s khởi động lại, image sandbox"
say "(${IMAGE}) biến mất khỏi cache — buộc phải pull lại từ registry, mà registry"
say "đó pull rất chậm. Wizard này pull MỘT LẦN, lưu ra file tar cục bộ, rồi cài 1"
say "service tự động import LẠI file tar đó (đọc đĩa, không qua mạng — nhanh) mỗi"
say "khi k3s khởi động. Cần sudo ở vài bước."

# All `ctr images` calls below use `-n k8s.io`: ctr defaults to the "default"
# namespace, but kubelet/Kubernetes only ever reads images from the "k8s.io"
# namespace — without this flag, pull/import "succeed" but the Pod scheduler
# still can't see the image and re-pulls from the (slow) registry anyway.

# ── Stage 1: pull once (idempotent, slow — the step the user flagged) ─────
stage "Pull image (một lần, có thể chậm)"
say "Nếu image đã có sẵn trong cache thì bỏ qua bước pull, không mất thời gian."
if sudo k3s ctr -n k8s.io images ls -q 2>/dev/null | grep -qxF "$IMAGE"; then
  ok "image đã có sẵn trong containerd cache — bỏ qua pull."
else
  warn "image chưa có trong cache — sẽ pull ngay bây giờ."
  note "registry này có thể CHẬM (vài phút là bình thường). Đừng Ctrl-C sớm."
  note "Nếu bị treo quá lâu (>10 phút không nhúc nhích), Ctrl-C rồi chạy lại wizard để thử lại."
  while true; do
    if sudo k3s ctr -n k8s.io images pull "$IMAGE"; then
      ok "pull thành công."
      break
    else
      err "pull thất bại (registry chậm/không tới được là nguyên nhân phổ biến nhất)."
      if confirm "Thử pull lại?"; then
        continue
      else
        err "Không có image thì không export/import được — wizard dừng ở đây."
        exit 1
      fi
    fi
  done
fi

# ── Stage 2: export to a local tar backup ──────────────────────────────────
stage "Export ra file tar cục bộ (backup)"
mkdir -p "$CACHE_DIR"
say "Lưu 1 bản backup image ra: $TAR_PATH"
say "Từ giờ về sau, việc 'khôi phục image sau reboot' chỉ là đọc file này từ đĩa —"
say "không đụng tới registry chậm kia nữa."
if sudo k3s ctr -n k8s.io images export "$TAR_PATH" "$IMAGE"; then
  sudo chown "$(id -u)":"$(id -g)" "$TAR_PATH" 2>/dev/null || true
  ok "đã export: $TAR_PATH ($(du -h "$TAR_PATH" 2>/dev/null | cut -f1))"
else
  err "export thất bại — kiểm tra dung lượng đĩa còn trống rồi chạy lại wizard."
  exit 1
fi

# ── Stage 3: install the boot-time re-import systemd unit ─────────────────
stage "Cài service tự động import lại mỗi khi k3s khởi động"
say "Tạo $UNIT_PATH — chạy sau k3s.service mỗi lần start (kể cả sau reboot),"
say "import lại image từ file tar ở Stage 2. Việc này là đọc đĩa cục bộ nên nhanh"
say "(vài giây), khác hẳn pull qua mạng."
UNIT_CONTENT="[Unit]
Description=Re-import cached AI Collective sandbox image into k3s containerd on boot
After=k3s.service
Requires=k3s.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/k3s ctr -n k8s.io images import ${TAR_PATH}
RemainAfterExit=yes
User=root

[Install]
WantedBy=multi-user.target
"
if printf '%s' "$UNIT_CONTENT" | sudo tee "$UNIT_PATH" >/dev/null; then
  ok "đã ghi $UNIT_PATH"
else
  err "không ghi được unit file — kiểm tra quyền sudo rồi chạy lại wizard."
  exit 1
fi

if sudo systemctl daemon-reload && sudo systemctl enable k3s-sandbox-image-warmup.service; then
  ok "đã enable — sẽ tự chạy ở mỗi lần boot từ giờ."
else
  err "enable thất bại."
  exit 1
fi

# ── Stage 4: test right now (no reboot needed) + verify ───────────────────
stage "Test ngay (không cần reboot) + xác nhận"
say "Chạy thử service ngay bây giờ để chắc chắn nó hoạt động, trước khi tin tưởng"
say "vào lần reboot tiếp theo."
if sudo systemctl start k3s-sandbox-image-warmup.service; then
  ok "service chạy xong."
else
  err "service chạy lỗi — xem chi tiết:"
  sudo systemctl status k3s-sandbox-image-warmup.service --no-pager || true
  exit 1
fi

note "trạng thái service:"
sudo systemctl status k3s-sandbox-image-warmup.service --no-pager | sed 's/^/  /'

printf '\n'
if sudo k3s ctr -n k8s.io images ls -q 2>/dev/null | grep -qxF "$IMAGE"; then
  ok "xác nhận: image có trong containerd cache ngay bây giờ."
else
  err "image vẫn KHÔNG thấy trong cache sau khi import — báo lại kết quả này, cần điều tra thêm."
fi

printf '\n'
say "Cách kiểm tra thật sự nghiêm ngặt (không cần reboot cả máy, chỉ cần restart k3s):"
step "sudo systemctl restart k3s.service"
step "đợi ~10-20s cho k3s lên lại, rồi: sudo k3s ctr -n k8s.io images ls -q | grep sandbox"
say "Nếu vẫn thấy image → service warmup hoạt động đúng, sẽ sống sót qua reboot thật."

finish
